version: "3.7"
services:
  conan-dedicated-server:
    container_name: conan-dedicated-server
    image: conandedicated:latest
    restart: unless-stopped
    environment:
      SERVER_STEAM_ACCOUNT_TOKEN: SERVER_STEAM_ACCOUNT_TOKEN
    ports:
      - 7777:7777/tcp
      - 7777:7777/udp
      - 27015:27015/tcp
      - 27015:27015/udp
      - 27016:27016/tcp
      - 27016:27016/udp
    volumes:
      - ./steamcmd:/steamcmd
      - ./game:/conan
      - ./winedata:/winedata
